Visual Uplifting of Pagination component.
myntra/applique-ui pull request #10
Opened 2022-03-16 12:05 UTC by saurabh33846

Changes for Visual Uplifting of pagination.

**Before**:
<img width="502" alt="Screenshot 2022-03-16 at 5 33 07 PM" src="https://user-images.githubusercontent.com/43277898/158585821-5eacca12-73af-437b-be0a-008193398f16.png">

**After**:
<img width="502" alt="Screenshot 2022-03-16 at 5 32 39 PM" src="https://user-images.githubusercontent.com/43277898/158585711-7c17f759-3e56-44eb-8b43-b5b3ad6cf3db.png">

2022-03-21 07:32 UTC, sunil-jhamnani commented on components/pagination/src/pagination.module.scss
> +  right: 0.15em;
We shouldn’t be using em's for spacing. Any reason for this?

2022-03-21 07:40 UTC, saurabh33846 commented on components/pagination/src/pagination.module.scss
> +  right: 0.15em;
When the font size is bigger and space is constant, it looks relatively closer to the Number.

2022-03-22 08:15 UTC, saurabh33846 commented on components/pagination/src/pagination.module.scss
> +  right: 0.15em;
Done

2022-04-01 12:20 UTC, sunil-jhamnani requested changes

2022-04-01 12:39 UTC, saurabh33846 commented on components/pagination/src/pagination.spec.js
> -
All these test cases are related to the arrow container. And since we removed that container, these test cases are not applicable.

2022-04-01 12:42 UTC, saurabh33846 commented on components/pagination/src/pagination.tsx
> +                <i className={classnames('select-chevron-down')} />
There is no icon available in uikit-icon package for the corresponding change. Icon is present in uikit-pro icon package, but that package is not publically available, so we can't use that also.

2022-04-18 09:40 UTC, sunil-jhamnani approved these changes

2023-06-06 09:08 UTC, closed without merging